# dev.ps1 — VirtuEx Windows dev launcher
#
# Usage (run from the repo root):
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\dev.ps1
#
# What it does:
#   1. Detects your machine's LAN IP automatically
#   2. Checks that the PostgreSQL Windows service is running (starts it if not)
#   3. Writes apps/web/.env.local with NEXT_PUBLIC_API_URL pointing to that IP
#   4. Launches the full Turbo dev stack with Next.js bound to 0.0.0.0
#      so other devices on the same network can reach both the frontend and API
#
# Requirements:
#   - PostgreSQL installed natively (https://www.postgresql.org/download/windows/)
#   - pnpm installed (https://pnpm.io/installation)
#   - Node.js installed (https://nodejs.org/)

# ── 1. Detect LAN IP ──────────────────────────────────────────────────────────

$LanIp = (
    Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object {
        $_.IPAddress -notmatch '^127\.' -and
        $_.IPAddress -notmatch '^169\.254\.' -and
        $_.PrefixOrigin -in @('Dhcp', 'Manual')
    } |
    Sort-Object -Property InterfaceMetric |
    Select-Object -First 1
).IPAddress

if (-not $LanIp) {
    Write-Error "[dev.ps1] ERROR: Could not detect LAN IP. Set NEXT_PUBLIC_API_URL manually in apps/web/.env.local."
    exit 1
}

Write-Host "[dev.ps1] Detected LAN IP: $LanIp" -ForegroundColor Cyan

# ── 2. Check / start PostgreSQL service ───────────────────────────────────────
#
# The installer registers a Windows service — usually named "postgresql-x64-<version>".
# We look for any service whose name starts with "postgresql".

$PgService = Get-Service -Name "postgresql*" -ErrorAction SilentlyContinue | Select-Object -First 1

if (-not $PgService) {
    Write-Warning @"
[dev.ps1] No PostgreSQL service found.
          Make sure PostgreSQL is installed: https://www.postgresql.org/download/windows/
          After installation, re-run this script.
"@
    exit 1
}

if ($PgService.Status -ne 'Running') {
    Write-Host "[dev.ps1] Starting PostgreSQL service '$($PgService.Name)'..." -ForegroundColor Yellow
    try {
        Start-Service -Name $PgService.Name
        # Wait up to 15 s for it to come up
        $PgService.WaitForStatus('Running', (New-TimeSpan -Seconds 15))
        Write-Host "[dev.ps1] PostgreSQL service started." -ForegroundColor Green
    } catch {
        Write-Error "[dev.ps1] Failed to start PostgreSQL service: $_"
        exit 1
    }
} else {
    Write-Host "[dev.ps1] PostgreSQL service '$($PgService.Name)' is already running." -ForegroundColor Green
}

# ── 3. Write apps/web/.env.local ─────────────────────────────────────────────

$EnvFile = "apps\web\.env.local"

@"
# Auto-generated by dev.ps1 — do not edit by hand
# Re-run .\dev.ps1 to update when your IP changes

NEXT_PUBLIC_API_URL=http://${LanIp}:3001
"@ | Set-Content -Encoding UTF8 $EnvFile

Write-Host "[dev.ps1] Wrote $EnvFile" -ForegroundColor Cyan
Write-Host "          NEXT_PUBLIC_API_URL=http://${LanIp}:3001" -ForegroundColor Cyan

# ── 4. Launch dev stack ───────────────────────────────────────────────────────
#
# NEXT_DEV_HOSTNAME=0.0.0.0 is picked up by the "dev" script in
# apps/web/package.json:  sh -c 'next dev --hostname ${NEXT_DEV_HOSTNAME:-localhost}'
#
# Note: On Windows, pnpm runs inside a cmd/powershell shell where sh -c is not
# available unless Git Bash / WSL is on PATH. If next dev fails to bind,
# install Git for Windows (https://git-scm.com/) which ships sh.exe.

$env:NEXT_DEV_HOSTNAME = "0.0.0.0"

Write-Host ""
Write-Host "[dev.ps1] Starting dev stack..." -ForegroundColor Green
Write-Host "          Frontend : http://${LanIp}:3000" -ForegroundColor Green
Write-Host "          API      : http://${LanIp}:3001" -ForegroundColor Green
Write-Host ""

pnpm dev
