#!/usr/bin/env sh
# dev.sh — VirtuEx local network dev launcher
#
# Usage:
#   chmod +x dev.sh
#   ./dev.sh
#
# What it does:
#   1. Detects your machine's LAN IP automatically
#   2. Starts (or restarts) the Postgres Docker container
#   3. Writes apps/web/.env.local with NEXT_PUBLIC_API_URL pointing to that IP
#   4. Launches the full Turbo dev stack with Next.js bound to 0.0.0.0
#      so other devices on the same network can reach both the frontend and API
#
# Requirements:
#   - Docker
#   - pnpm
#   - Node.js

set -e

# ── 1. Detect LAN IP ──────────────────────────────────────────────────────────

LAN_IP=$(ip route get 1 2>/dev/null | awk '{print $7; exit}')

if [ -z "$LAN_IP" ]; then
  # Fallback for macOS / BSD
  LAN_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)
fi

if [ -z "$LAN_IP" ]; then
  echo "[dev.sh] ERROR: Could not detect LAN IP. Set NEXT_PUBLIC_API_URL manually in apps/web/.env.local."
  exit 1
fi

echo "[dev.sh] Detected LAN IP: $LAN_IP"

# ── 2. Start Postgres container ───────────────────────────────────────────────

if docker inspect postgres_vtx > /dev/null 2>&1; then
  # Container exists — make sure it is running
  if [ "$(docker inspect -f '{{.State.Running}}' postgres_vtx)" != "true" ]; then
    echo "[dev.sh] Starting existing postgres_vtx container..."
    docker start postgres_vtx
  else
    echo "[dev.sh] postgres_vtx is already running."
  fi
else
  echo "[dev.sh] Creating and starting postgres_vtx container..."
  docker run \
    --name postgres_vtx \
    -p 5432:5432 \
    -v postgres_vtx:/var/lib/postgresql/ \
    -e POSTGRES_PASSWORD=postgres \
    -d postgres
fi

# Give Postgres a moment to be ready on a cold start
echo "[dev.sh] Waiting for Postgres to be ready..."
RETRIES=10
until docker exec postgres_vtx pg_isready -U postgres > /dev/null 2>&1 || [ "$RETRIES" -eq 0 ]; do
  RETRIES=$((RETRIES - 1))
  sleep 1
done

if [ "$RETRIES" -eq 0 ]; then
  echo "[dev.sh] WARNING: Postgres may not be ready yet — continuing anyway."
else
  echo "[dev.sh] Postgres is ready."
fi

# ── 3. Write apps/web/.env.local ─────────────────────────────────────────────

ENV_FILE="apps/web/.env.local"

cat > "$ENV_FILE" << EOF
# Auto-generated by dev.sh — do not edit by hand
# Re-run ./dev.sh to update when your IP changes

NEXT_PUBLIC_API_URL=http://$LAN_IP:3001
EOF

echo "[dev.sh] Wrote $ENV_FILE:"
echo "         NEXT_PUBLIC_API_URL=http://$LAN_IP:3001"

# ── 4. Launch dev stack ───────────────────────────────────────────────────────
#
# NEXT_DEV_HOSTNAME=0.0.0.0 tells the custom Next.js dev server to bind on all
# interfaces so devices on the LAN can reach http://<LAN_IP>:3000.
# The API (Express) already listens on 0.0.0.0 by default.

echo "[dev.sh] Starting dev stack..."
echo "         Frontend : http://$LAN_IP:3000"
echo "         API      : http://$LAN_IP:3001"
echo ""

NEXT_DEV_HOSTNAME=0.0.0.0 pnpm dev
